version: '3'

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: "go-postgres"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_PORT:-5432}:5432"
volumes:
  postgres:
    driver: local