version: '3'

services:
  app:
    image:  cosmtrek/air
    container_name: "app"
    volumes:
      - ./:/usr/app
    environment:
      air_wd: "/usr/app"
    networks:
      - gofiber
    ports:
      - "${FORWARD_APP_PORT:-8080}:${APP_PORT:-8080}"
  postgres:
    image: postgres:15.1-alpine
    container_name: "postgres"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
    networks:
      - gofiber
    ports:
      - "${FORWARD_DB_PORT:-5432}:${DB_PORT:-5432}"
  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - "redis:/data"
    networks:
      - gofiber
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
networks:
  gofiber:
    driver: bridge
volumes:
  postgres:
    driver: local
  redis:
    driver: local